### ISSUE TITLE
TKN - this logo is outdated

### ISSUE THREAD

**Issue by gkucmierz** [monzanifabio/cryptofont#1]
<img width="144" alt="Zrzut ekranu 2019-12-13 o 07 33 29" src="https://user-images.githubusercontent.com/739084/70774616-147ada80-1d7b-11ea-88e5-3c7d6670d007.png">
<img width="282" alt="Zrzut ekranu 2019-12-13 o 07 34 53" src="https://user-images.githubusercontent.com/739084/70774619-15ac0780-1d7b-11ea-98f8-0d57dfbde5da.png">

**Comment by monzanifabio** [comment]
Thanks for the correction.
It'll be amended soon.

**Comment by monzanifabio** [comment]
@gkucmierz the TKN token and many others have been updated to their latest version on release 1.1.0
