### ISSUE TITLE
Wrong css selector `i` instead of `i.cf`

### ISSUE THREAD

**Issue by antiFetzen** [monzanifabio/cryptofont#11]
Hey,

first of all cool project and a big thanks! 🤩 

I get in struggle on the first implementation.
All `<i>` elements changed to unknown cryptofont icons. 🤔 

I checkt the `cryptofont.css`and found the following lines:

https://github.com/monzanifabio/cryptofont/blob/29d4d92b9f7a8a02d0139c2a2718a133d7745bf6/cryptofont.css#L13-L26

In my opinion, an error has slipped in here.

The usage is
```HTML
<i class="cf cf-btc"></i> 
```

shouldn't the [cryptofont.css](https://github.com/monzanifabio/cryptofont/blob/master/cryptofont.css) be as follows?

```css
 i.cf {    /* use !important to prevent issues with browser extensions that change fonts */
  font-family: 'cryptofont' !important;
  speak: never;
  font-style: normal; 
```

Cheers
Chris

**Comment by monzanifabio** [comment]
Hi Chris, have you got any other fonts on your website like Fontawesome?
Sometimes they might get in conflict.

**Comment by ahadabasi** [comment]
> Hi Chris, have you got any other fonts on your website like Fontawesome?
> Sometimes they might get in conflict.

Hi
To prevent conflict with other fonts like fontawesome:
It should be `font-family: 'cryptofont'; ` Not `font-family: 'cryptofont' !important; `

**Comment by monzanifabio** [comment]
Thanks for the feedback.
I will further investigate the issue.

**Comment by antiFetzen** [comment]
> Hi Chris, have you got any other fonts on your website like Fontawesome?
> Sometimes they might get in conflict.

Hey
yes, I'm also using fontawesome within my project.

Thanks for your support!

**Comment by monzanifabio** [comment]
Issue fixed in the last release
