### ISSUE TITLE
Add lens protocol logo to cryptofont

### ISSUE THREAD

**Issue by dineshpinto** [monzanifabio/cryptofont#18]
Hi, 

Lens Protocol is a composable and decentralized social graph from the builders of Aave

Website: https://lens.xyz

Thanks

**Comment by monzanifabio** [comment]
Hi @dineshpinto, thank you for the suggestion.
We have added Lens Protocol to our brand section.
You can find the Lens logo here [https://cryptofonts.com/brands.php](https://cryptofonts.com/brands.php)
