### ISSUE TITLE
Font is pixelated on some devices

### ISSUE THREAD

**Issue by oneezy** [monzanifabio/cryptofont#3]
On some devices the font is pixelated.

I did a little bit of research on this and one possible solution would be rearranging `@font-face` urls so that `svg` comes first. I haven't verified that this works though.. https://stackoverflow.com/questions/9272073/why-are-my-google-web-fonts-pixelated#answer-14905091

I also haven't tried any css font smoothing tricks yet.

![image](https://user-images.githubusercontent.com/7369575/85079124-abda4380-b18b-11ea-9356-f674d54f44f1.png)

**Comment by monzanifabio** [comment]
Hi @oneezy thank you for bringing this up.
I'll look into the issue in more details.
Could you please let me know what device is causing the problem and what OS you're running?
Thanks

**Comment by oneezy** [comment]
no problem and thanks for the quick response!

I actually **fixed** the issue by updating to the latest version of Chrome.

Users that are still running the old version of Chrome will experience the issue. 

In the old version of Chrome I can confirm that:
- This was an issue with the [web font icons](https://cryptofonts.com/icons.php) only and not the [svg color icons](https://cryptofonts.com/coloricons.php).
- Both the [material.io](https://material.io/resources/icons/?style=baseline) and [materialdesignicons.com](https://materialdesignicons.com/) icon fonts are smooth. 
---
In regards to the svg url, in version [1.1.0](https://cdn.jsdelivr.net/gh/monzanifabio/cryptofont@1.1.0/cryptofont.css) it appears that the `svg` is the last on the list (not first). 
```
@font-face {
  font-family: 'cryptofont';
  src:  url('fonts/cryptofont.eot?ruc2ox');
  src:  url('fonts/cryptofont.eot?ruc2ox#iefix') format('embedded-opentype'),
    url('fonts/cryptofont.ttf?ruc2ox') format('truetype'),
    url('fonts/cryptofont.woff?ruc2ox') format('woff'),
    url('fonts/cryptofont.svg?ruc2ox#cryptofont') format('svg');
  font-weight: normal;
  font-style: normal;
  font-display: block;
}
```
