### ISSUE TITLE
MISSING ICON: Bitcoin Cash (BCH)

### ISSUE THREAD

**Issue by oneezy** [monzanifabio/cryptofont#4]
Could you add **Bitcoin Cash (BCH)** to the web font and color svg icons?

https://github.com/mirgj/cryptocurrency-icons-font/blob/master/src/svg/color/bch.svg

![image](https://user-images.githubusercontent.com/7369575/85185255-dba34d00-b258-11ea-8ac2-b0fdb2e93ef0.png)

**Comment by monzanifabio** [comment]
@oneezy We are currently reviewing all the missing icons in the font especially for the top 200 from Coinmarketcap.
Although the Bitcoin cash logo is present in the svg icons section using the official logo from [https://www.bitcoincash.org/](https://www.bitcoincash.org/)

You can find it here:
[https://github.com/monzanifabio/cryptoicons/blob/1.8.84/SVG-icons/bch.svg](https://github.com/monzanifabio/cryptoicons/blob/1.8.84/SVG-icons/bch.svg)

**Comment by monzanifabio** [comment]
@oneezy BCH has been added and will be available in the next release together with many other icons.
You can have a sneak peek in the new-release branch :)
