### ISSUE TITLE
Conflict with Font-awesome

### ISSUE THREAD

**Issue by gabrielbr** [monzanifabio/cryptofont#6]
Using !important on line 15 on cryptofont.css overrides other fonts as font-awesome.

**Comment by monzanifabio** [comment]
Hi @gabrielbr in some cases it doesn't depending on how you import your css file in your <head>
We added !important just as a safety measure.
Are you having any problem using both fonts?

**Comment by gabrielbr** [comment]
Hi @monzanifabio . thanks for the reply.
yeah, it was overriding when it shouldn't. 
im importing as:
<link href="assets/plugins/crypto-font/cryptofont.css" rel="stylesheet">
<link href="assets/plugins/font-awesome/css/all.min.css" rel="stylesheet">

And managed to get it working removing the !important on line 15
`font-family: 'cryptofont';`

**Comment by monzanifabio** [comment]
Thanks for letting me know and glad you solved your issue.
Another thing that we suggest in our troubleshooting guide is to just replace the tag from `<i>` to `<span>` which is actually more semantically correct and should do the trick.
