### ISSUE TITLE
GIX icon missing

### ISSUE THREAD

**Issue by nacr** [monzanifabio/cryptofont#7]
hey I was checking your work but I cant find GIX Coin icon.

Tks

**Comment by monzanifabio** [comment]
Hi @nacr, unfortunately, we were unable to find GIX on either Coinmarketcap or Coingecko.
Are you sure the ticker is correct?

**Comment by nacr** [comment]
Yes, GIX is listed on coinsbit https://coinsbit.io/trade/GIX_EUR

And also simex

**Comment by monzanifabio** [comment]
We will review the token and if we get enough information it'll be added.
Thanks for the suggestion 👍

**Comment by nacr** [comment]
Hi @monzanifabio if you need anything just ask.
I can point you in the right direction.

Tks

**Comment by nacr** [comment]
Btw GIX is on Cryptocompre

https://www.cryptocompare.com/coins/gix/overview/EUR
